### ISSUE TITLE
API documentation broken?

### ISSUE THREAD

**Issue by andrewkern** [popgensims/stdpopsim#112]
Guys does the API documentation look broken to you? @ndukler @jeromekelleher 

https://stdpopsim.readthedocs.io/en/latest/

It doesn't seem to be rendering correctly for some reason.

**Comment by jeromekelleher** [comment]
Tried a fix; let's see if that sorts it out.

**Comment by jeromekelleher** [comment]
Yep, sorted. Thanks for spotting it @andrewkern!
