### ISSUE TITLE
Documentation for CLI

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/stdpopsim#118]
We need some documentation for the CLI. At a minimum we want:

- CLI docs generated by [sphinx_argparse](https://sphinx-argparse.readthedocs.io/en/stable/)

- A section of the tutorial showing how to use it.

**Comment by ndukler** [comment]
I can work on this.

**Comment by ndukler** [comment]
@jeromekelleher This looks awesome! Can we make the output of `stdpopsim species --help` a little less verbose. Maybe add a `--show-model-details` or something so that we don't get all the model text?

**Comment by ndukler** [comment]
What exactly do you have in mind for the CLI docs? As in a subheading for an example CLI use for each model under the catalog like we used to have? I'll get on the tutorial though.

**Comment by jeromekelleher** [comment]
> What exactly do you have in mind for the CLI docs? As in a subheading for an example CLI use for each model under the catalog like we used to have? I'll get on the tutorial though.

Sphinx arg-parse should handle most of it -- won't really know until we try it out and see what the output looks like.

A tutorial section would be **super** helpful though!

**Comment by jeromekelleher** [comment]
I think we can close this with #165 and #197.
