### ISSUE TITLE
Analysis notebook needed for GutenkunstThreePopOutOfAfrica model

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/stdpopsim#12]
We need some analysis of the GutenkunstThreePopOutOfAfrica model to verify that it is correctly implemented. This should be in the form of a Jupyter notebook (stored in a new directory, say ``notebooks``). This can serve as a example for our model QC process.

**Comment by ndukler** [comment]
I'll get on it, sorry for the delay.

**Comment by andrewkern** [comment]
@ndukler, it looks like @jgallowa07 has done this and has a PR pending [here](https://github.com/popgensims/stdpopsim/pull/30). I'll assign you as a reviewer there if that's okay?

**Comment by ndukler** [comment]
Sure, sorry for the delay, I've been working on a talk for next week.

Noah

On Mar 9, 2019 4:30 PM, Andrew Kern <notifications@github.com> wrote:

@ndukler<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ndukler&d=DwMCaQ&c=mkpgQs82XaCKIwNV8b32dmVOmERqJe4bBOtF0CetP9Y&r=jMMeS7wwmWCiZ0Euaii__A&m=MrgWPI4s2cPeL15jCH56kZDQKs3Tm-z5hfUW-oYhJiA&s=j2GItqoIMGu1yDh-ORsECx-dSKnb3i7iKVQdjrM5Yus&e=>, it looks like @jgallowa07<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jgallowa07&d=DwMCaQ&c=mkpgQs82XaCKIwNV8b32dmVOmERqJe4bBOtF0CetP9Y&r=jMMeS7wwmWCiZ0Euaii__A&m=MrgWPI4s2cPeL15jCH56kZDQKs3Tm-z5hfUW-oYhJiA&s=y0isSjSuZFC93lwt4cCImZngM8ODhcCYsskqgDO8tz8&e=> has done this and has a PR pending here<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_popgensims_stdpopsim_pull_30&d=DwMCaQ&c=mkpgQs82XaCKIwNV8b32dmVOmERqJe4bBOtF0CetP9Y&r=jMMeS7wwmWCiZ0Euaii__A&m=MrgWPI4s2cPeL15jCH56kZDQKs3Tm-z5hfUW-oYhJiA&s=y1Yex9JEtUBQrDOZwzY3xucnfGmcH_2RZl2I1sfqjUw&e=>. I'll assign you as a reviewer there if that's okay?

**Comment by ndukler** [comment]
Based on a quick look at what Jared did a few thoughts which either @jgallowa07 or I can do, whichever has time first: (1) The color scale for the joint SFS looks like it is in linear scale, might be better to put it in log scale to match the paper (2) if we can get our hands on the original simulated data we can plot the residuals from their simulated data. Do either of these seem like a good idea/possible?

**Comment by ndukler** [comment]
Also, if we can get our hands on some of the original data, we can make comparative plots for the other simple metrics as well. Would that be a useful more general strategy where the original simulation data/code still exists somewhere?

**Comment by ndukler** [comment]
More TODOs (mostly for myself): (1) Match y-axis scales for SFS plots for [9]. (2) Implement the projection method (supplemental 3.1) to better match paper? (3) Add some commentary on why sanity checks make sense.

**Comment by jgallowa07** [comment]
As a quick reply without too much thought; the tree sequence should be in
the directory? Or I might be confused about the last message :)

But I agree, I’m happy to put that plot on the log scale as soon as I get
back to my computer tomorrow night.

Thanks for pointing that out.

Best,
-Jared

**Comment by ndukler** [comment]
Thanks! By original simulated data I meant from the 2009 paper. I doubt it's around anymore but I figured we'd ask b/c it's make it really easy to do a bunch of comparisons. It might be a more useful strategy when the paper/model is more recent and thus easier to get the data. Sorry I'm a bit slow on the coding myself, python isn't one of my primary languages so I'm a bit slow on coding with it/I'm not familiar with the python popgen tools.

**Comment by ndukler** [comment]
Looking at the excellent work done by @jgallowa07 , I've been thinking about what we need from the QC notebook. The main issue I have with the current approach is that there is no real way of deciding when the implemented model is correct/incorrect. I get that we're probably looking for gross mismatches between the results from the paper and the popsim simulations, but it can be non-trivial to exactly match the data processing (and even visualization) in the paper to the point where I can be confident that there are no bugs (at least from pure visual inspection of plots). For me then it comes down to deciding what we want to test. If we just are checking to make sure that the model is correctly implemented, I propose that the QC person looks at the paper, and re-implements the model in a separate script without popsim. Then the results of that simulation and the popsim simulation can be compared under uniform processing, visualization, and summary statistics. This is inspired by how I ten to write functional tests, where I implement a specific, relatively easy, calculation by hand and compare it to the results of a more general function in the software I'm developing. Thoughts @jeromekelleher @andrewkern @jgallowa07 ?

**Comment by jeromekelleher** [comment]
I like the idea @ndukler, and it's a good test. It might be argued that this is a unit test though: two different implementations of the same model should be identical, and so there's no point in running simulations at all.

I agree though, having a separate (blind) implementation of the model in as part of the QC notebook would be a good addition. We can always adapt the code to incorporate it as a unit test afterwards.

**Comment by andrewkern** [comment]
The problem I see here is we then have to QC the separate implementation in some way, so we now have two potential sources of error. 

In the brief bit that I've looked over the results from @jgallowa07 it immediately became clear that default parameters from the human model were off, and we quickly were able to spot a problem with the mutation rate. I.e., it was instantly helpful. We've just begun the effort to have a QC notebook to be shared, so I'd encourage trying this out a bit longer before we move to a more complex system of QC. 

my two cents

**Comment by jeromekelleher** [comment]
> The problem I see here is we then have to QC the separate implementation in some way, so we now have two potential sources of error.

That's my point though @andrewkern, the should be precisely equal. There's no randomness here, so the demographic model you compute using one method should be identical to the other. We can provide a method in the package somewhere to compare two demographic models for equality.

Most of these models should be fairly simple, so a section in which the model is implemented (and fully described, using Markdown text) could be quite a useful way to start things off.

**Comment by ndukler** [comment]
Just to add on to @jeromekelleher , the other key bit is that the second implementation is blind, potentially directly from the paper itself, which would catch any copying/parameterization errors made in the original transfer from paper to model.

**Comment by andrewkern** [comment]
not sure I follow then-- will the QC team's independent implementation use the stdpopsim code?

**Comment by ndukler** [comment]
Not as I imagined it at least

**Comment by jeromekelleher** [comment]
> not sure I follow then-- will the QC team's independent implementation use the stdpopsim code?

No, they try to implement it from the paper, in the notebook, blind to the stdpopsim implementation. We then compare the two for exact equality. If everyone has agreed, then they should be identical (modulo numerical precision).

**Comment by andrewkern** [comment]
ok but they would be using `msprime` at least for this?

**Comment by jeromekelleher** [comment]
> ok but they would be using msprime at least for this?

Sure, yeah, the goal is to create a list of population configurations, demographic events and a migration matrix (which we can wrap up in a stdpopsim.Model). Comparing this with the 'official' stdpopsim Model implementing the model in question gives a really good verification, and would weed out misunderstandings. 

It basically means that we do two independent msprime descriptions for each model. If both these descriptions are identical, then we're a lot more confident that there aren't silly mistakes.

**Comment by andrewkern** [comment]
okay this sounds decently well defined. presumably we will be looking at expectations of summary statistics between the QC implementation and the production one-- should we think about using the analysis `snakemake` workflow for the QC as well rather than this simpler notebook?

**Comment by jeromekelleher** [comment]
> presumably we will be looking at expectations of summary statistics between the QC implementation and the production one-- should we think about using the analysis snakemake workflow for the QC as well rather than this simpler notebook?

No, there's no need for simulations! Think about the migration matrix, for example. This is the calculation:

```python
source_model = stdpopsim.GutenkunstOutOfAfrica()
qc_model = # defined somewhere else in the notebook
assert np.allclose(source_model.migration_matrix, qc_model.migration_matrix)
```
That's it. The other parts of the model (demographic events and pop configs) are a little more fiddly, but it's the same principle. It's a deterministic description of a model which we can compare for equality with another deterministic description of the same model.

**Comment by jgallowa07** [comment]
To sum up, you want someone to implement the model a second time, without *peaking* at the official model, and compare the characteristics?

**Comment by jeromekelleher** [comment]
That's about it @jgallowa07! Although it's going to be quite tricky to do this for the Gutenkunst model, since this is in the msprime documentation for defining population models...

**Comment by jgallowa07** [comment]
Hmm, this may be a conflict of interest for me. Maybe it's better for somebody with more expertise to do? If not I'm happy to attack this, It's just more likely I'll put a bug in the replicated model.

**Comment by ndukler** [comment]
I would have a potentially similar problem, but for different reasons since I have no experience with msprime so I would have to look at the example code ... which is the  Gutenkunst model.

**Comment by ndukler** [comment]
Also, is there a compare() function for two msprime objects?

**Comment by jeromekelleher** [comment]
> Also, is there a compare() function for two msprime objects?

No, I'll make one to compare two stdpopsim models in this repo though.

**Comment by ndukler** [comment]
@jeromekelleher I think we can close this down now :)

**Comment by jeromekelleher** [comment]
Agreed!
