### ISSUE TITLE
provide msprime-to-SLiM translation

### ISSUE THREAD

**Issue by petrelharp** [popgensims/stdpopsim#132]
The first choice to make here is whether

a) we first implement using WF models (porting over SLiMe?), or
b) we start out wtih non-WF models

Contrary to what I said before, we should probably do (a). 

I propose that put this code in a new file, `stdpopsim/slim_backend.py`.

**Comment by grahamgower** [comment]
I started on a SLiM backend. Comments welcome.
https://github.com/grahamgower/stdpopsim/tree/slim

**Comment by petrelharp** [comment]
Awesome. Could you start a PR to this repo so it's easier to see what changes you've made?

**Comment by petrelharp** [comment]
Looking good generally.

**Comment by grahamgower** [comment]
Can close this. Merged to slim-engine-dev branch with #163.

**Comment by jeromekelleher** [comment]
Done.
