### ISSUE TITLE
scan docs for improvement

### ISSUE THREAD

**Issue by petrelharp** [popgensims/stdpopsim#137]
Make a pass through the docs to determine what things are unclear and/or out of date, either fixing or adding issues to fix the parts that are lacking.

**Comment by agladstein** [comment]
I can work on this! 
(you can add me as an assignee and also add a "good first issue" label)

**Comment by agladstein** [comment]
I finished going through the docs and added a bunch of issues. Most of them are small improvements, but I think mostly necessary before publication.

**Comment by gtsambos** [comment]
I'm doing this now, too -- will reference here. (Happy to take these on myself, also)

**Comment by gtsambos** [comment]
(you can assign me too pls)

**Comment by jeromekelleher** [comment]
I think we can close this now? There's lots of individual issues open now to track things.

**Comment by jeromekelleher** [comment]
I'm going to close - if someone objects, shout out, and I'll open it again.
