### ISSUE TITLE
Add Tennyson et. al model

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/stdpopsim#14]
Port the description from [here](https://github.com/popgensims/demographicModels/blob/master/tennessen_ceu_msprime.py). Should include documentation and analysis notebook. 

See also #13 and #14.

**Comment by jeromekelleher** [comment]
#22 added a basic implementation. We still need documentation and analysis though.

**Comment by ndukler** [comment]
So I've been writing the QC script for this model, and it kinda quickly became obvious that, for whatever reason, working from the primary paper, the model is somewhat ambiguous. There are multiple parameter sets, multiple possible interpretations of which migration parameters should be included etc. For example, it's not obvious which of the three parameter sets inferred in Gavel was used in Tennessen (although it seems to be the low-coverage + exons), nor is it obvious what happens to the migration rates with respect to the first and second population growth periods. I'll bring this up at the next chat, just thought I'd make a note of it here in case anyone had any ideas.

**Comment by ndukler** [comment]
Additionally, my calculations lead to a somewhat different current European population size than what Tennessen shows in figure 2B. It is entirely possible that I am just bad at this, but the African calculation seems to be correct so it makes me a little suspicious.

**Comment by jeromekelleher** [comment]
Nice work @ndukler --- sounds like a good discussion point for today's meeting!

**Comment by ndukler** [comment]
@carjed Which ID numbers did you use for the CEU and YRI populations?

**Comment by carjed** [comment]
I'm using AF=0 and EU=1, to be consistent with the GutenkunstThreePop model, which uses AF=0, EU=1, and AS=2

**Comment by ndukler** [comment]
Thanks!

**Comment by ndukler** [comment]
@jeromekelleher Can we close down this issue?
