### ISSUE TITLE
Introduction docs

### ISSUE THREAD

**Issue by agladstein** [popgensims/stdpopsim#142]
Add some more information in the introduction section.
- refer to paper?
- Goals of the project.
- who is stdpopsim for?
- brief overview of types of things it can be used for.

sub-issue of #137

**Comment by gtsambos** [comment]
I think this can be closed now because of #223.

**Comment by jeromekelleher** [comment]
Done --- we can reopen if people disagree.

**Comment by agladstein** [comment]
I think it looks great. Thanks @gtsambos!
