### ISSUE TITLE
Should CLI write to stdout by default

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/stdpopsim#143]
The CLI currently writes to a file given by a mandatory command line argument at the moment, i.e.:
```
$ stdpopsim homsap 10 tmp.trees
```
arguably, this should write the output to stdout, and have have an optional ``-o filename`` argument, i.e.

```
$ stdpopsim homsap 10 > tmp.trees
```
or 
```
$ stdpopsim homsap 10 -o  tmp.trees
```

Writing to stdout is more flexible and conforms to unix conventions better. The only downside is that, because the trees file is a binary format, it's easy to break your terminal by accident if you forget to redirect.

This is an important design decision, so it'd be good to get some thoughts on it. Pinging @popgensims/all

**Comment by reedacartwright** [comment]
I also think that writing to stdout is a good idea. If we are concerned
about writing binary output to the terminal, we can require the -o flag and
requires users to use -o - to write to stdout.

--
Reed A. Cartwright, PhD
Barrett Honors Faculty
Assistant Professor of Genomics, Evolution, and Bioinformatics
School of Life Sciences
Human and Comparative Genomics Laboratory
The Biodesign Institute
Arizona State University
==================
Availability: http://links.asu.edu/CartwrightCalendar
Address: The Biodesign Institute, PO Box 875301, Tempe, AZ 85287-5301 USA
Packages: The Biodesign Institute, 1001 S. McAllister Ave, Tempe, AZ
85287-5301 USA
Office: Biodesign B-220C, 1-480-965-9949
Website: http://cartwrig.ht/

**Comment by jeromekelleher** [comment]
OK, that's settled then --- dumping binary to stdout by default it is.
