### ISSUE TITLE
Allow ``species.genome["chr22"]``?

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/stdpopsim#16]
Currently we use 
```python
from stdpopsim import homo_sapiens
chrom = homo_sapiens.genome.chromosomes["chr22"]
```
to access a particular chromosome for a species. This is a bit clunky. We would set it up so that 

```
from stdpopsim import homo_sapiens
chrom = homo_sapiens.genome["chr22"]
```
does the same thing (but keep the ``.chromosomes`` as well, for clarity. We could also add synonyms for the chromosomes, such that ``homo_sapiens.genome["chr22"]`` and ``homo_sapiens.genome["22"]`` return the same thing.

Any thoughts?

**Comment by andrewkern** [comment]
I like the idea of synonyms but think it’s low priority 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jeromekelleher** [comment]
Not relevant to new API in #110.
