### ISSUE TITLE
Drop daquiri or make conda package?

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/stdpopsim#161]
The daiquiri package is used to make setting up logging easier and get coloured output for messages. It's not essential, but it is useful. Unfortunately, it's not packaged on conda.

Therefore, we either need to drop daiquiri, or create a package for it on conda-forge.

**Comment by agladstein** [comment]
When this is resolved, we must also update the docs warning (https://stdpopsim.readthedocs.io/en/latest/development.html#installation)
