### ISSUE TITLE
SLiM engine development

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/stdpopsim#170]
With #163 we have some really excellent initial code for incorporating SLiM in as a full and optional simulation engine.

However, we also want to drop our first stable release in the next few weeks, and we don't want to include the extra dependencies and not fully tested approach of the SLiM engine in there (I think? Please disagree if you think the SLiM engine *should* be in the first release).

So, we don't want to merge in the SLiM code to master yet, but we also want to be able to develop it. I see two options:

1. The SLiM development goes ahead on @grahamgower's branch, and he keeps track of upstream changes by periodically rebasing.
2. We keep a long-lived dev branch in this repo (``slim_engine``) which we develop on until after the initial 0.1 version is released. We can periodically update this, and then merge it into master. 

There pros and cons to both approaches, but I think if several people want to work incrementally on the SLiM engine then we'll need to go with option 2.

Any thoughts?

**Comment by grahamgower** [comment]
Maybe it's best to just keep things in my branch for now, so as not to distract from the stable release. But could we come up with a list of things that should be there before being merged into master, so I have something to aim for? The main things I can think of now are:

* Feature parity with msprime engine.
  - Support msprime.MassMigration with proportion < 1.
  - Support recombination maps.
* Burn in (currently using 10*Ne generations rule-of-thumb). Should instead have a choice of:
  - Proper within-SLiM burn-in by checking for coalescence in each ancestral population.
  - Recapitation and neutral-mutation overlay with pyslim.
* Check/fix migration rate indexes.
* Add model/species/etc. citations to the generated SLiM script.
* Add population labels as comments in the generated SLiM script.
* Check trees files have similar properties to those made with msprime.
  - Anything other than summary stats?
* Add SimulationEngine class to stdpopsim.
  - To contain: engine name, CLI args, citations, supported features, etc.
  - Add entries for msprime.simulate and slim_simulate.
* Test framework.

**Comment by jeromekelleher** [comment]
This looks just right to me @grahamgower .

**Comment by grahamgower** [comment]
#255 #256 #257 #258 #259 #260 #261 #262 #263 #264 #265

**Comment by jeromekelleher** [comment]
Added these to the slim engine project: https://github.com/popgensims/stdpopsim/projects/1

**Comment by jeromekelleher** [comment]
Going to close this issue as we have an ongoing project to track it.
