### ISSUE TITLE
Generic IM model

### ISSUE THREAD

**Issue by ckyriazis** [popgensims/stdpopsim#171]
As discussed on our call today, it would be great to have a generic IM model as a way to test the two population analysis pipeline under a scenario where there is not model misspecification. Ideally, this model would have three population size parameters (Na, N1, N2) one divergence parameter (Tdiv) and two migration rate parameters (M12 and M21).

**Comment by apragsdale** [comment]
@ckyriazis are you working on this? I'm happy to put this together if no one else is already.

**Comment by jeromekelleher** [comment]
Go for it I'd say @apragsdale, ping me if you'd like any help!

**Comment by jeromekelleher** [comment]
There you go, it's official now; you're assigned!

**Comment by ckyriazis** [comment]
Thanks @apragsdale !

**Comment by grahamgower** [comment]
The comment in the header for this model doesn't match the defined populations. I.e.
```
    Takes parameters N0, N1, N2, T, M12, and M21, as list of arguments:
    (NA, N1, N2, T, M12, M21).
    Sampling is disallowed in population index 0, as this is the ancestral
    population.
```
But then the populations definition has the ancestral population last.
```
populations = [_pop0, _pop1, _popAnc]
```

**Comment by apragsdale** [comment]
You're right, good catch. Labels switched around after some discussion of how to label and define pops, and I overlooked the comment. I can push a fix to this this afternoon.

**Comment by apragsdale** [comment]
FYI I think this can be closed, no? (I've since learned the "Closes #xxx" trick in PRs)
