### ISSUE TITLE
fixed-size generic model tutorial

### ISSUE THREAD

**Issue by agladstein** [popgensims/stdpopsim#173]
a fixed-size generic model (like what we have but with more words), then outputting to (a) a tped file and (b) a vcf

I will work on this.

From list in https://github.com/popgensims/stdpopsim/issues/139

**Comment by agladstein** [comment]
For the tped, should I just do this with some python via the `genotype_matrix`? or is there some utility that I don't know about that prints to tped and tfam?

**Comment by andrewkern** [comment]
there is stuff out there but not sure how much we want to depend on other code? e.g., https://github.com/pontussk/vcf2tped.py

**Comment by agladstein** [comment]
nah, I'll just write a little Python.
