### ISSUE TITLE
 No module named 'appdirs'

### ISSUE THREAD

**Issue by agladstein** [popgensims/stdpopsim#174]
Funny thing, I'm working on https://github.com/popgensims/stdpopsim/issues/156 and I can't get docs to compile.

I followed the dev docs as is and did:
```python3 -m pip install -r requirements/development.txt```

Then,
```
cd docs/
make
```

And I get the error:
```
Running Sphinx v2.2.0

Extension error:
Could not import extension speciescatalog (exception: No module named 'appdirs')
make: *** [html] Error 2
```

Similarly, if I also add
```
python3 -m pip3 install -r requirements/rtd.txt
```
I get the same error. 

I don't have any errors when doing the pip installs.

**Comment by agladstein** [comment]
I just tried with conda

```
conda config --add channels conda-forge
conda install --file=requirements/development.txt
```

and got the error:
```
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - daiquiri
```
Looks like `daiquiri` isn't available on conda.

**Comment by agladstein** [comment]
This was fixed with

```
pip3 install -r requirements/development.txt
pip3 install -r requirements/rtd.txt
```

So, my guess is using `python3 -m pip3` installed to a different Python version.

**Comment by jeromekelleher** [comment]
Hmm, looks like you've got some path issues here all right.

**Comment by agladstein** [comment]
Also, the `venv` instructions I included in https://github.com/popgensims/stdpopsim/pull/176 worked for me. Who knows how my paths for messed up. I'm sure this happens to many people and using a virtual environment will probably get around the issue.
