### ISSUE TITLE
dev docs virtual env

### ISSUE THREAD

**Issue by agladstein** [popgensims/stdpopsim#178]
I think it would be helpful to encourage people to use virtual environments (I think this would have prevented the problem I had https://github.com/popgensims/stdpopsim/issues/174). 
So, I think we should just include instructions on how to do that for `pip` and `conda` in the development installation section.
This is probably also useful to include in the general installation section.

sub-issue of https://github.com/popgensims/stdpopsim/issues/137

I can add this into the docs.

**Comment by jeromekelleher** [comment]
SGTM, thanks @agladstein

**Comment by jeromekelleher** [comment]
Closed in #176 

(ps. adding a line 'Closes #176' in the git commit would have closed this automatically @agladstein --- it's quite handy when knocking off multiple issues in a single PR)

**Comment by agladstein** [comment]
ooh thanks for letting me know!
