### ISSUE TITLE
tutorial port old examples

### ISSUE THREAD

**Issue by agladstein** [popgensims/stdpopsim#179]
There is a TODO section in the Tutorial RTD with examples. 
It says port port these old examples.
I'm not sure what needs to be ported here. 
Do we still want to include these examples?

- simple simulation of human chromosome 22
- various genetic maps
- demographic model

(This issue should be included in the "Write more docs" project)

**Comment by jeromekelleher** [comment]
This was a reference to some older examples that seem to be done now. I think we can just remove this TODO and close the issue, tbh. Things have moved on a lot.
