### ISSUE TITLE
more docs for PiecewiseConstantSize

### ISSUE THREAD

**Issue by agladstein** [popgensims/stdpopsim#180]
More docs need to be added to the `PiecewiseConstantSize` class. 
Should have a description of what the model is. What are the input parameters?

sub-issue of #137

**Comment by jeromekelleher** [comment]
Good call. The arguments are 
- N0, the population size at time zero
- Each subsequent argument is a tuple (t, N) which gives the time at which the size change takes place and the time.

It's best illustrated by an example:
```python
model1 = stdpopsim.PiecewiseConstantSize(N0, (t1, N1)) # One change
model2 = stdpopsim.PiecewiseConstantSize(N0, (t1, N1), (t2, N2)) # Two changes
# etc
```
Does that make sense?

**Comment by agladstein** [comment]
Yes. I can add this in!

**Comment by agladstein** [comment]
Are we using `doctest` to include examples in the API docs?

**Comment by jeromekelleher** [comment]
> Are we using doctest to include examples in the API docs?

No, not at the moment. I've never been a big fan of it, but happy to include it if you want to set things up.

**Comment by agladstein** [comment]
I've never used it before. I was just looking for a way to include that example in the docstring because I thought it was helpful.

**Comment by jeromekelleher** [comment]
Can just use

```
:code-block: python
    # example code
```
