### ISSUE TITLE
Error in the BrowningAmerica ADMIX population

### ISSUE THREAD

**Issue by ndukler** [popgensims/stdpopsim#185]
The description and sampling scheme for the ADMIX population is incorrect. The population is modern, not ancient and sampling should be permitted.

**Comment by ndukler** [comment]
I will address this in #177 if that's okay because otherwise some of the versioning will get hairy if that's okay @jeromekelleher ?

**Comment by jeromekelleher** [comment]
Sure, sounds good. It would be good if you could address the issue in a separate commit (ideally, containing a line "'Closes #177" in the body of the commit message)

**Comment by jeromekelleher** [comment]
Good catch btw.
