### ISSUE TITLE
name change from popSim to stdpopsim?

### ISSUE THREAD

**Issue by andrewkern** [popgensims/stdpopsim#188]
Hey all-- I'm wondering if we should consider an official name change of the project. In working on the manuscript I did a quick google search. There are currently 46,000 hits for "popSim". For "stdpopsim" there are 181 and they are all to our project. What if we officially dub this thing "stdpopsim"?

**Comment by dschride** [comment]
No.

**Comment by petrelharp** [comment]
I also like popsim better, although you make a good argument.

**Comment by petrelharp** [comment]
Hm:
![Screenshot from 2019-11-22 17-15-46](https://user-images.githubusercontent.com/1046249/69470491-c2cacb80-0d4b-11ea-9a08-02a8838a50df.png)

**Comment by andrewkern** [comment]
exactly my point @petrelharp

**Comment by dschride** [comment]
Perhaps we could change this by talking about and linking to pop sim on our websites, maybe making a little webpage with that title, etc. Probably wouldn't take too much effort to take over the name.

**Comment by jeromekelleher** [comment]
I think it's a good idea for the software (stdpopsim) and the consortium (PopSim) to have different names. I don't think stdpopsim would be a good name for the consortium, so I'd vote against a name change there.

I agree PopSim isn't terribly Google-unique, but it's pretty hard to get good names these days that are. If you google for "PopSim consortium" it's all us, so I think that's probably OK?

**Comment by Chris1221** [comment]
I agree with Jerome about software/consortium separation, but I have always been slightly confused about why the organisation name (`popgensims`) is actually neither of them. I've had to manually direct some people here because googling "popsim github" doesn't lead you here -- would it be a thought to standardise the organisation name with the consortium name?

**Comment by jeromekelleher** [comment]
Looks like we can't change the name of the github organisation to "popsim" as someone is using it: https://github.com/POPSIM

**Comment by jeromekelleher** [comment]
Since we've take the decision to rename the GitHub organisation to "popsim_consortium", I'm going to close this issue.
