### ISSUE TITLE
Docs/API: `Species` parameter defaults

### ISSUE THREAD

**Issue by gtsambos** [popgensims/stdpopsim#192]
At the moment, I'm having a bit of overall difficulty understanding which parameters are 'settable' by the user, which are fixed, and why the default values are as they are.

I find it odd that the `Species` objects have attributes for population sizes and generation times, as well as for their citations (which are all empty lists, btw), but not for mutations. Does this mean that every `stdpopsim` simulation uses the same mutation rate? Also, btw, many of these numbers look very round and even, like 'guesstimates' rather than something from a paper. Given that there are also `citation` attributes, I worry that `stdpopsim` users (especially students and other popgen newbies) might mistake these numbers for some 'consensus estimate' of these values from the literature. There's also a danger that users may think that these parameter values are used in the manuscript-specific models -- I only realised that there were not because of the note in the API, which could easily be missed.

Another Q: given that the manuscript model classes use their own parameter values, are these attributes actually *needed* anywhere? I've only had a cursory look, but it looks to me like the only place where they might be needed is as an input into a 'generic' simulation model, and if so, I don't think you'd lose much by making the user input their own population sizes etc. If this is the case, I think it would be better to remove these attributes entirely.

subissue of #137

**Comment by jeromekelleher** [comment]
> I find it odd that the Species objects have attributes for population sizes and generation times, as well as for their citations (which are all empty lists, btw), but not for mutations. Does this mean that every stdpopsim simulation uses the same mutation rate? Also, btw, many of these numbers look very round and even, like 'guesstimates' rather than something from a paper. Given that there are also citation attributes, I worry that stdpopsim users (especially students and other popgen newbies) might mistake these numbers for some 'consensus estimate' of these values from the literature. There's also a danger that users may think that these parameter values are used in the manuscript-specific models -- I only realised that there were not because of the note in the API, which could easily be missed.

We should totally have proper values for these, from the literature and with citations.

Mutation rates should be per-chromosome, and are accessed via the Contig interface.

> Another Q: given that the manuscript model classes use their own parameter values, are these attributes actually needed anywhere? I've only had a cursory look, but it looks to me like the only place where they might be needed is as an input into a 'generic' simulation model, and if so, I don't think you'd lose much by making the user input their own population sizes etc. If this is the case, I think it would be better to remove these attributes entirely.

Some models use a specific ``generation_time``, and some don't. It's messy. We definitely do need the basic values though, because these are used the in the default simulation (which is a single population), and they're also useful for instantiating generic models.

**Comment by gtsambos** [comment]
Okay, I'll see if I can dig up some references for these values.
I don't know so much about the other species, but you wouldn't typically see whole-species estimates of Ne in humans because they aren't considered a single panmictic population -- there must be something out there though, perhaps from an older paper.

**Comment by jeromekelleher** [comment]
Yeah, embarrassingly I have no idea where the 10**4 estimate for humans comes from!

**Comment by andrewkern** [comment]
we can definitely find something from like 1998 to cite for that!

**Comment by jeromekelleher** [comment]
Superseded by #289.

@gtsambos, please feel free to reopen this if it's no fully resolved by putting in good estimates and citations for the generation time and population size.
