### ISSUE TITLE
tutorial on 'how to interpret the data'

### ISSUE THREAD

**Issue by gtsambos** [popgensims/stdpopsim#195]
See #137 and #151. I'm happy to take this on.

**Comment by jeromekelleher** [comment]
All yours @gtsambos!

**Comment by jeromekelleher** [comment]
Is this covered by the PR you merged a few days ago @gtsambos? (It's good if the PR/commit can refer back to the issue to make keeping track of things easier)

**Comment by gtsambos** [comment]
I was initially thinking this would be a totally separate tute, but actually, @agladstein's tute about generating vcfs (#234) covers a lot of the ground I was thinking of. I think in between this tutorial and the various "Example analysis" tutes that are in the works, it might not be necessary to have a whole new one that's just about interpreting the data.

**Comment by agladstein** [comment]
I think that's fine for now. We can always add another tutorial later if there is feedback that it's not clear.
