### ISSUE TITLE
Docs/API: List of CLI options

### ISSUE THREAD

**Issue by gtsambos** [popgensims/stdpopsim#197]
At the moment, the docs don't show users how the CLI works, or what options there are. I know @ndukler is working on a tutorial to show how some of these work in #165, but it would be good to have a list of all of the possible arguments (including all of the possible species, recombination maps, model arguments) somewhere in the docs too. Either on an API page, or elsewhere.

Subissue of #137

**Comment by andrewkern** [comment]
you are doing the lord's work here @gtsambos!

**Comment by gtsambos** [comment]
👼 👼 👼

**Comment by jeromekelleher** [comment]
A good option here would be to use [sphinx-argparse](https://sphinx-argparse.readthedocs.io/en/stable/) to automatically render the CLI help output in HTML. Otherwise we end up having two versions of the same docs, which inevitably drift.

**Comment by gtsambos** [comment]
> A good option here would be to use sphinx-argparse to automatically render the CLI help output in HTML.

Okay, I can look into this next week. Just saw you mentioned it in #118  as well.
