### ISSUE TITLE
Add --dry-run option to CLI

### ISSUE THREAD

**Issue by ndukler** [popgensims/stdpopsim#199]
Add flag to allow users to see exactly what they're going to run before they run it. Output includes the species and model names, the numbers of samples from each population, and the sampling times. This will probably be done by adding a `dry_run` parameter to the `simulate()` function in each engine and update the abstract class appropriately.

**Comment by jeromekelleher** [comment]
I think we can do this without involving the Engine --- we just write out a report about the ``engine``, ``contig``, ``model`` and ``samples`` objects that we would have passed to the simulate method.

OK if I assign this one to you?

**Comment by ndukler** [comment]
Sure. I think that having the dry run being a property of the engine might be better in the long run though if the way different engines produce the dry run output differs. I suppose I sort of think how the dry run goes is a property of the engine. What do you think?

**Comment by jeromekelleher** [comment]
Well, I guess it might need to become a property of the engine at some point, but I think it's a good idea to keep all the interface code within the ``cli`` module. Let's just do it the easy way for now, and avoid the complications of formatting output text from outside the CLI module.

**Comment by ndukler** [comment]
Do we want the python API to have the ability to do a dry run as well?

**Comment by jeromekelleher** [comment]
No --- this is just for the CLI.

**Comment by ndukler** [comment]
Ok, makes more sense to keep it in the `cli` module then. I'll get on it

**Comment by jeromekelleher** [comment]
If the API is well designed, a dry-run text output will be no more informative than the code for creating the simulation. Reading the code should be like a dry run.

**Comment by ndukler** [comment]
I think once we have the key-value pairs for the sampling set up that will definitely be true, so I'll throw up an issue for that as well. Feel free to assign it to me :)

**Comment by jeromekelleher** [comment]
Thinking about it this morning, perhaps it would be good to write this report out by default before running the simulation? We're already writing out the citation information, so perhaps a concise report of what the simulation did would be a good idea as well. We can turn this off using the ``--quiet`` option.

The ``--dry-run`` option then would do everything except run the simulation. What do you think?

**Comment by ndukler** [comment]
Sounds good to me!

**Comment by jeromekelleher** [comment]
Any updates on this @ndukler? I'd like to get this feature in for 0.1.0, if possible.

**Comment by ndukler** [comment]
Sorry, I've been busy with some of my other projects. I'll try to get it done today.
