### ISSUE TITLE
CLI install dev docs

### ISSUE THREAD

**Issue by agladstein** [popgensims/stdpopsim#206]
Under the RTD Development, Installation section we may want to also include installation instructions for the CLI.
I'm assuming this is:
```
python setup.py install
```

sub-issue of https://github.com/popgensims/stdpopsim/issues/137

**Comment by jeromekelleher** [comment]
This is done automatically when you run ``pip install stdpopsim`` or ``conda install stdpopsim``

**Comment by jeromekelleher** [comment]
If you want to run the CLI during development, use ``python3 -m stdpopsim`` in the project root directory.

**Comment by agladstein** [comment]
But, `pip install stdpopsim` and `conda install stdpopsim` don't work yet?

So, for development, you should just `python3 -m pip install -r requirements/development.txt` and then `python3 -m stdpopsim` will work?

**Comment by jeromekelleher** [comment]
> So, for development, you should just python3 -m pip install -r requirements/development.txt and then python3 -m stdpopsim will work?

Yep.
