### ISSUE TITLE
Improve CLI help output

### ISSUE THREAD

**Issue by gtsambos** [popgensims/stdpopsim#215]
Some of the help output in the CLI could be clearer. I'm going to make a pull request to deal with some relatively minor things (typos etc), but have some bigger questions that I'll turn into separate issues to log here.

**Comment by jeromekelleher** [comment]
I think we've done some good work here --- can we close down this meta issue?

**Comment by gtsambos** [comment]
Yes -- I think we're now at the point where individual issues for specific features will suffice
