### ISSUE TITLE
Length multiplier -- ambiguous descriptions

### ISSUE THREAD

**Issue by gtsambos** [popgensims/stdpopsim#216]
after reading through all the relevant bits of docs/help and the `get_contig` API, I'm still a little confused about how the `length-multiplier` option is actually changing the simulation. If I specify an msprime simulation with length multiplier 0.5 and some pre-specified chromosome and recombination rate, am I just simulating the first half of this chromosome? Or am I scaling all of the entries in the recombination map by 0.5 so that there are ~half as many mutations between any given positions? ( like, simulating every second SNP in the chromosome)?

In other words, does this parameter affect the number of mutations, or the number of trees in the simulation? Most of the current wording leaves both interpretations open -- for example, the CLI help entry for the -l options is:

```
  -l LENGTH_MULTIPLIER, --length-multiplier LENGTH_MULTIPLIER
                        Simulate a chromsome of length l times the named
                        chromosome
```

This could be documented more clearly in the `get_contig` API and CLI help (see #215 ), especially if this functionality is eventually to be extended to non-uniform recombination rates

**Comment by gtsambos** [comment]
NB. This will be particularly consequential if people end up doing haplotype/IBD -based analyses with these simulations (which should soon be possible in tskit...)

**Comment by andrewkern** [comment]
right so my understanding here is that this option alters the genetic map length simulated. It only works with a uniform recombination map, e.g., no empirical maps. So if we imagine that 4NrL is the population effective recombination rate across the whole simulated chunk defined by a `stdpopsim` contig, by invoking `--length-multiplier` we are effectively scaling that down the sequence length, L, over which recombination can occur.

**Comment by jeromekelleher** [comment]
It is doing something very simple --- if X is the physical length of a given chromosome, then we can use this option to run a simulation with ``length`` =  l * X. So, if I want to simulate something that is 10% the length of human chromosome 1, I use ``stdpopsim homsap -c chr1 -l 0.1``. This doesn't work with genetic maps --- I think we'd need a different interface for doing that, which would need ``start`` and ``end`` coordinates. The ``--length-multiplier`` is still handy even if we have this more precise approach because (I at least) find it very hard to remember exactly how many zeros I need to type when working in genome coordinates, and these kind of quick-and-dirty simulations are handy when we don't necessarily care about the fine details of recombination maps.

**Comment by gtsambos** [comment]
>  So, if I want to simulate something that is 10% the length of human chromosome 1, I use stdpopsim homsap -c chr1 -l 0.1.

okay, so to be clear: it's specifying that the we are simulating some representative sub-interval of the whole chromosome that spans 10% of the physical length of the entire chromosome? 

I think I'll change some of the wording to make this interpretation a bit more unambiguous

**Comment by jeromekelleher** [comment]
> okay, so to be clear: it's specifying that the we are simulating some representative sub-interval of the whole chromosome that spans 10% of the physical length of the entire chromosome?

Yes --- since it's all uniform, there no difference between any particular 10% of the chromosome. You could also use it to simulate something that twice the length of a particular chromosome, hence the ``--length-multiplier`` rather than ``--length-fraction`` or whatever.

**Comment by jeromekelleher** [comment]
Also, the ``sequence_length`` of the tree sequence you get back will be 10% the length of the chromosome.

**Comment by jeromekelleher** [comment]
What's the status here @gtsambos?

**Comment by gtsambos** [comment]
Sorry -- will make a small pull request to edit some of the wording later today/tomorrow
