### ISSUE TITLE
Default 'flat' recombination maps

### ISSUE THREAD

**Issue by gtsambos** [popgensims/stdpopsim#217]
Most of the API/help for the recombination inputs say something like this (which I took from the CLI help)

```
  -g , --genetic-map    Specify a particular genetic map. If no genetic map is
                        specified use a flat map by default. Available maps:
```

A flat map is a uniform recombination rate, right? It's not clear where users can find out what this uniform rate is.

Subissue of #215 and #137

**Comment by jeromekelleher** [comment]
We could say "By default, we use a chromosome-specific uniform recombination rate." The recombination rates for each chromosome are in the catalog and online docs.

**Comment by jeromekelleher** [comment]
"flat map" is not a good choice of terminology though, we should change it.

**Comment by gtsambos** [comment]
Okay, I'll do this.

**Comment by jeromekelleher** [comment]
What's the status of this @gtsambos?

**Comment by gtsambos** [comment]
Sorry, haven't gotten round to this yet. I can submit a mini pull request and change a few lines of wording later tonight so we can close this --
