### ISSUE TITLE
QC for new Arabidopsis model (HuberTwoEpoch)

### ISSUE THREAD

**Issue by andrewkern** [popgensims/stdpopsim#226]
Started a PR for this new model here https://github.com/popgensims/stdpopsim/pull/225

Anyone up for QC? This should be quite straight forward as the model params are plainly listed in this supplement: https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-018-05281-7/MediaObjects/41467_2018_5281_MOESM1_ESM.pdf

**Comment by ndukler** [comment]
I can handle this.

**Comment by andrewkern** [comment]
thanks @ndukler. take a look at table S1 for the two epoch model params. once we merge this we might as well do the three epoch model too

**Comment by ndukler** [comment]
@andrewkern The model got merged in without rebasing. Could you quickly set master back one commit , then rebase the `athal_huberModel` then re-merge it?

**Comment by ndukler** [comment]
To clarify, not the QC model, PR #225 .

**Comment by andrewkern** [comment]
sorry to be dense here-- where is the issue? looks like a single commit?

**Comment by ndukler** [comment]
It is a single commit. It just wasn't rebased against the head of master before it was merged.

**Comment by ndukler** [comment]
Ok, I have the QC model ready.

**Comment by andrewkern** [comment]
so should I revert, rebase, and then merge for you?

**Comment by ndukler** [comment]
Yeah, that should do it. Sorry for the inconvenience :(

**Comment by ndukler** [comment]
Can we close this down @andrewkern
