### ISSUE TITLE
implement three epoch Huber et al model for a_thal

### ISSUE THREAD

**Issue by andrewkern** [popgensims/stdpopsim#228]
here is a link to the parameter table: https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-018-05281-7/MediaObjects/41467_2018_5281_MOESM1_ESM.pdf

**Comment by andrewkern** [comment]
here is the doi for the paper: https://doi.org/10.1038/s41467-018-05281-7

**Comment by noscode** [comment]
See PR [#270](https://github.com/popgensims/stdpopsim/pull/270)

**Comment by ndukler** [comment]
We can close this @andrewkern
