### ISSUE TITLE
Rename the 'america' model of American admixture

### ISSUE THREAD

**Issue by gtsambos** [popgensims/stdpopsim#235]
could we possibly rename the `america` model to something a bit more specific? Given that this demography doesn't have any Native American people or anyone from Central/South America in it

(perhaps `afr_america`, since this putative purpose of this demography was to model African-American admixture?)

(also also: perhaps the same criticism applies to our `africa` model? But I don't know as much about that particular one)

**Comment by jeromekelleher** [comment]
SGTM @gtsambos --- I'm not keen on the current names at all, so any suggestions welcomed. More generally, see #122.

**Comment by gtsambos** [comment]
closed by #310
