### ISSUE TITLE
Output ACGT mutations instead of 0/1

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/stdpopsim#241]
Msprime defaults to generating infinite sites with the classical 0/1 haplotype values (making it easy to see which is the ancestral and derived states). However, it also supports generating infinite sites mutations from the ACGT alphabet. The tree sequence still has complete information about which state is ancestral.

I'm guessing most users would prefer/expect ACGT mutations?

**Comment by apragsdale** [comment]
Do you envision having a catalog of mutation models here, or just randomly assigning mutations from ACGT (which I guess is a very simple mutation model)? That could be quite useful, but possibly a lot of work to compile various mutation models.

**Comment by jeromekelleher** [comment]
Ultimately we'd like to have a catalog of mutation models as well, yeah. These'll need to be implemented first though. For now, we just randomly assign an ancestral state from ACGT and a derived state from the remainder.

**Comment by andrewkern** [comment]
having the nucleotide output as an option would be good. yeah.

**Comment by jeromekelleher** [comment]
> having the nucleotide output as an option would be good. yeah.

Option or default though? I don't see much reason for having the old-school 0/1 mutations other than that's the way it's always been done.

**Comment by dschride** [comment]
I would vote for 'option', since some users might want to plug their output directly into summary stat calculations, and many tools for this expect 0/1.

**Comment by jeromekelleher** [comment]
OK, cool. Any ideas on the interface? ``--mutation-model/-u [model_id]`` maybe? Defaults to ``infinite_sites_nucleotides`` and also available is ``infinite_sites_01``?

**Comment by dschride** [comment]
Yeah I think that would be fine.

**Comment by ndukler** [comment]
Can we separate the mutational model and the output form? That way any model can have 0/1 or ACGT based output.

**Comment by jeromekelleher** [comment]
I think 0/1 really only makes sense in the most naive infinite sites case. Any other model depends on the actual nucleotide values, so wouldn't really make sense. As I say, there's no loss of information here: the ancestral/derived states are stored in the tree sequence and it's trivial to get 0/1 numeric values out using the genotype_matrix method. We're not offering any direct textual output anyway, and conversion to VCF will have the REF allele set to the ancestral state. 

So, my take would be to just offer ``infinite_sites_nucleotides`` as the default (and only option) for the initial release, and we can add the 0/1 model later if someone actually asks for it.

How does this sync with how SLiM does things @grahamgower?

**Comment by grahamgower** [comment]
I haven't used the nucelotide recording features of SLiM, but I guess this will be fine. Probably the more common use case will be to do recapitation and add mutations onto a tree sequence with msprime anyway, in which case this should be seamless.

**Comment by jeromekelleher** [comment]
What's the default mutation model in SLiM though, if we were simulating some selected sites, say? Sorry, dumb questions here!

**Comment by grahamgower** [comment]
0/1 is the default.

**Comment by jeromekelleher** [comment]
Ah, OK, thanks. I'll work up a PR as a proposal, see what people think.

**Comment by jeromekelleher** [comment]
OK, since most people seem to be happy with 0/1 as the default, I'm going to close this issue and leave 0/1 mutations as our only option for now. We can think about how to do mutation models properly at a later date.
