### ISSUE TITLE
typo in CLI help homo

### ISSUE THREAD

**Issue by agladstein** [popgensims/stdpopsim#242]
currently homsap CLI help says:
```
Default population parameters for Homo sapiens:
Generation time: 25
Population size: 10000
Mutation rate: 1e-08
Recombination rate: 1.203828130094258e-08
```
Looks like mutation rate and recombination rate values have been switched!

looks like this is a sub-issue of https://github.com/popgensims/stdpopsim/issues/215

**Comment by jeromekelleher** [comment]
Not sure this is a typo --- we only have one mutation rate for humans now, see #17. See [this line](https://github.com/popgensims/stdpopsim/blob/master/stdpopsim/catalog/homo_sapiens.py#L61).

**Comment by agladstein** [comment]
Ok. Not a typo. Just not the correct mutation rate right now. I'll close this issue because it stems from https://github.com/popgensims/stdpopsim/issues/17
