### ISSUE TITLE
Change parameter to "--bibtex-file",

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/stdpopsim#244]
I just noticed in #214 we added an option ``--bibtex_file``. This should be ``--bibtex-file`` for consistency. Also, we should add a short version (-b I guess?)

What do you think @Chris1221?

**Comment by Chris1221** [comment]
Yep, I didn't consider consistency with the other options (and the short `b` should definitely be there). I'll put in a PR to fix this and the writing of the genetic map citations today.

**Comment by jeromekelleher** [comment]
Closed in #245.

FYI @Chris1221, if you add a line "Closes #XYZ" to your commit message GitHub will close the issue automatically for you.
