### ISSUE TITLE
Docs: investigate using sphinxcontrib-programoutput for docs

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/stdpopsim#266]
There is a sphinx plugin for including program output into sphinx docs. We could use this for thinks like the tutorial for including the output of ``stdpopsim --help``.  It has a reasonable chance of working I think, and would be pretty handy.

Anyone want to try it out?

https://pythonhosted.org/sphinxcontrib-programoutput/

**Comment by gtsambos** [comment]
sure!

**Comment by agladstein** [comment]
That would be great.

**Comment by gtsambos** [comment]
See my pull request #268
