### ISSUE TITLE
CLI docs named args table unaligned

### ISSUE THREAD

**Issue by agladstein** [popgensims/stdpopsim#267]
The tables in the CLI docs showing named arguments are not lined up correctly. I assume the arguments and the description should be in the same row.

(e.g. https://stdpopsim.readthedocs.io/en/latest/cli_arguments.html#Named%20Arguments_repeat1)

maybe related to https://github.com/popgensims/stdpopsim/pull/222
and https://github.com/popgensims/stdpopsim/issues/197

**Comment by jeromekelleher** [comment]
Looks OK to me --- can you put in a screenshot of what you're seeing please?

**Comment by agladstein** [comment]
See how some of the variables are not in the same line as their description? That's on RTD, not locally compiled.

<img width="761" alt="Screen Shot 2019-12-07 at 11 02 01 AM" src="https://user-images.githubusercontent.com/26617086/70377298-05121200-18e1-11ea-9489-85f01d4fdc55.png">

<img width="745" alt="Screen Shot 2019-12-07 at 11 01 51 AM" src="https://user-images.githubusercontent.com/26617086/70377299-05121200-18e1-11ea-9ecd-73499ec02957.png">

**Comment by jeromekelleher** [comment]
I think that's standard for argparse --- it only does this where the argument length is greater than some value. You'd need to raise this upstream I think (looks fine to me though, I'm not sure what else you would do)

**Comment by agladstein** [comment]
Looks like this is resolved from one of the many recent PRs haha. not sure which one fixed it.
I like this better.

Now it looks like:
<img width="742" alt="Screen Shot 2019-12-08 at 10 22 46 AM" src="https://user-images.githubusercontent.com/26617086/70391581-b29a2980-19a4-11ea-8aa5-80e8a2a38601.png">

**Comment by jeromekelleher** [comment]
> Looks like this is resolved from one of the many recent PRs haha. not sure which one fixed it.
I like this better.

Cool! I have no idea what happened there, must have been an updated release of sphinx-argparse!
