### ISSUE TITLE
Model parameter tables missing

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/stdpopsim#272]
When we build the docs, the catalog is only partially built because we're missing CSV parameter tables for some models:

Skipping model parameters for zigzag due to missing table
Skipping model parameters for kamm_ancient_eurasia due to missing table
Skipping model parameters for SMA_1pop due to missing table
Skipping model parameters for Afr_2epoch due to missing table

It would be good to clean this up, and update the ``speciescatalog.py`` generator to emit a warning when they are missing (which would cause CI to fail if new models are added without parameter tables.).

**Comment by agladstein** [comment]
I want to keep an eye on this.

**Comment by noscode** [comment]
I can help with that

**Comment by jeromekelleher** [comment]
That would be great, thanks @noscode!

When you're adding the tables, it's good to build the docs locally (see [here](https://stdpopsim.readthedocs.io/en/latest/development.html#documentation)) so you can see the parameter tables rendered in the catalog like [this one](https://stdpopsim.readthedocs.io/en/latest/catalog.html#sec_catalog_homsap_models_americanadmixture_4b11)

**Comment by noscode** [comment]
See PR#[133](https://github.com/popgensims/stdpopsim/pull/333)

**Comment by jeromekelleher** [comment]
Closed in #333
