### ISSUE TITLE
interface from models to msprime DemographyDebugger broken?

### ISSUE THREAD

**Issue by andrewkern** [popgensims/stdpopsim#273]
i'm running some of the new models through the `n_t` analysis pipeline and have been updating the `Snakefile` to keep up `stdpopsim` development.

As part of `analysis` we use the `DemographyDebugger` class from `msprime` to calculate the expected truth using `coalescence_rate_trajectory()`. We were instantiating the debugger by casting our model as a dict
https://github.com/popgensims/analysis/blob/897ea5ea70e59c368311277d7e5f6577ff7ef7d1/n_t/plots.py#L69

seems like the `asdict` call no longer works? do we just need to add a decorator for dataclass? i.e., https://docs.python.org/3/library/dataclasses.html

**Comment by grahamgower** [comment]
Its probably safer if you explicitly give the DemographyDebugger the parameters it wants.
```
msprime.DemographyDebugger(
            population_configurations=model.population_configurations,
            migration_matrix=model.migration_matrix,
            demographic_events=model.demographic_events)
```

You might be able to get it to work with `DemographyDebugger(**vars(model))`, but any attributes added to `Model` in the future will break calling in this manner. (And I plan to add more attributes very soon).

**Comment by andrewkern** [comment]
yeah it probably is, i agree. this was a very convenient way to do things though.

**Comment by jeromekelleher** [comment]
We're trying to make the Model class a bit less tightly bound to the way msprime works, so I'm not over keen on adding back ``asdict`` --- it's either limiting what we can add as attributes, or inaccurately named.

What if we added a method ``get_demography_debugger()``, which will return an instance of ``msprime.DemographyDebugger``?

**Comment by andrewkern** [comment]
I can take a shot at this

**Comment by andrewkern** [comment]
closed by https://github.com/popgensims/stdpopsim/pull/313
