### ISSUE TITLE
Readthedocs builds broken after CLI output

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/stdpopsim#274]
As (mostly) expected, the rtd builds are broken after we merged #268. I'll sort it out.

```
System Message: ERROR/6 (/home/docs/checkouts/readthedocs.org/user_builds/stdpopsim/checkouts/latest/docs/tutorial.rst, line 38)

Command 'stdpopsim homsap --help' failed: [Errno 2] No such file or directory: 'stdpopsim': 'stdpopsim'
```

**Comment by agladstein** [comment]
I'm currently having this issue.
What install instructions should fix this (if this is fixed)?

**Comment by gtsambos** [comment]
Are you getting the error that Jerome posted above, or another one?

**Comment by gtsambos** [comment]
Have you installed sphinxcontrib-commandoutput or whatever it's called? There are more things in the development requirements now so might need to install them again

**Comment by agladstein** [comment]
yes, it's the same error posted above. 
I just reinstalled according to the instructions we have up. https://stdpopsim.readthedocs.io/en/latest/development.html#installation

**Comment by petrelharp** [comment]
Huh, they built fine for me, after I installed sphinxcontrib-commandoutput.

**Comment by agladstein** [comment]
`sphinxcontrib-programoutput`? yes, it's in the requirements/development.txt

**Comment by jeromekelleher** [comment]
I think the issue you have might be that the ``stdpopsim`` binary isn't available in your PATH @agladstein. Can you check that please?

**Comment by agladstein** [comment]
I think it should be in my PATH.
I have 
```
AriellasNewMBP:stdpopsim agladsteinNew$ echo $PATH
/usr/local/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/anaconda3/bin://anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin
AriellasNewMBP:stdpopsim agladsteinNew$ which stdpopsim
/anaconda3/bin/stdpopsim
```

and when I'm in a virtual env
```
(stdpopsim_env) AriellasNewMBP:stdpopsim agladsteinNew$ echo $PATH 
/Users/agladsteinNew/dev/stdpopsim/stdpopsim_env/bin:/Users/agladsteinNew/.pyenv/plugins/pyenv-virtualenv/shims:/Users/agladsteinNew/.pyenv/shims:/Users/agladsteinNew/.pyenv/bin:/usr/local/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/anaconda3/bin://anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/anaconda3/bin://anaconda/bin
(stdpopsim_env) AriellasNewMBP:stdpopsim agladsteinNew$ which stdpopsim
/anaconda3/bin/stdpopsim
```

If I explicitly add it to my path within the virtual env:
```
(stdpopsim_env) AriellasNewMBP:docs agladsteinNew$ echo $PATH 
/anaconda3/bin/stdpopsim:/usr/local/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/anaconda3/bin://anaconda/bin:/Users/agladsteinNew/dev/stdpopsim/stdpopsim_env/bin:/Users/agladsteinNew/.pyenv/plugins/pyenv-virtualenv/shims:/Users/agladsteinNew/.pyenv/shims:/Users/agladsteinNew/.pyenv/bin:/usr/local/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/anaconda3/bin://anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/anaconda3/bin://anaconda/bin
(stdpopsim_env) AriellasNewMBP:docs agladsteinNew$ make
Running Sphinx v2.2.0

Extension error:
Could not import extension sphinxcontrib.programoutput (exception: No module named 'sphinxcontrib.programoutput')
make: *** [html] Error 2
```

**Comment by jeromekelleher** [comment]
Ah, OK --- so ``sphinxcontrib-programoutput`` isn't installed even though it's in ``requirements/development.txt``. This must be an issue with your local setup, as it's working fine for others I think.

**Comment by agladstein** [comment]
it says it's installed when I install it manually with `pip`.
I wonder if it's because when I'm in the virtual env with `requirements/development.txt` installed and have `stdpopsim` in the path, it's the wrong `stdpopsim` (i.e. the one I installed from `python -m pip install stdpopsim --user`).

**Comment by agladstein** [comment]
Yes, that was it. I had to build the development version of `stdpopsim` in the virtual environment so it wouldn't use the other version.
