### ISSUE TITLE
How can non-python programmers help?

### ISSUE THREAD

**Issue by reedacartwright** [popgensims/stdpopsim#29]
I don't program in Python, and seems that this project is going to be Python based. Any recommendations on how I can help?

**Comment by jeromekelleher** [comment]
Well stdpopsim is definitely Python based as it's a Python module for defining standard population genetics simulation models. However, we do need another repo for running tools on data simulated from these models, which may or may not be Python based. As I said on the mailing list, we need to figure out what this repo should be called, create it, and get discussion going there on how we organise things.

(Going to close this issue as it's not directly related to this repo)
