### ISSUE TITLE
dromel generation_time/population_size values and citations

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/stdpopsim#290]
We need citations for the generation time and population size in D mel. These are defined [here](https://github.com/popgensims/stdpopsim/blob/master/stdpopsim/catalog/drosophila_melanogaster.py#L49). 

Please note in particular the "wildly wrong" comment for Ne=10**4 in dromel.

Can someone who knows about these things propose the correct values and citations for these please?

**Comment by jeromekelleher** [comment]
@andrewkern, any thoughts on papers here/people to ask?

**Comment by andrewkern** [comment]
so i've got a good, old citation from the 70's for Ne ~13000 but the paper has no doi! https://www.ncbi.nlm.nih.gov/pubmed/4207116

can i put the html link to the paper instead of a doi?

**Comment by andrewkern** [comment]
we could also cite Kreitman (1983) who estimated Ne to be ~3x10^6 from Adh data. I prefer the former citation though as it's a classic, genome-wide estimate that wasn't from DNA sequence data.

**Comment by jeromekelleher** [comment]
Crud, no doi is a PITA (our bibtex system depends on it).

Also, isn't a it a bit worrying that one is 10^4 and the other is 10^6?

**Comment by andrewkern** [comment]
closed by https://github.com/popgensims/stdpopsim/pull/321
