### ISSUE TITLE
esccol generation_time citation

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/stdpopsim#291]
We need a citation for the e coli genome definition [here](https://github.com/popgensims/stdpopsim/blob/master/stdpopsim/catalog/e_coli.py#L36)

@fbaumdicker, IIRC you added the e coli model. Would you mind tracking this down and updating please?

**Comment by fbaumdicker** [comment]
I updated the citation and created a pr.

**Comment by jeromekelleher** [comment]
Thanks @fbaumdicker!
