### ISSUE TITLE
aratha generation_time/population_size values and citations 

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/stdpopsim#293]
We need citations for the generation time and population size in A thaliana. These are defined [here](
https://github.com/popgensims/stdpopsim/blob/master/stdpopsim/catalog/arabidopsis_thaliana.py#L41)

Can someone who knows about these things propose the correct values and citations for these please?

**Comment by andrewkern** [comment]
i asked twitter today about this https://twitter.com/pastramimachine/status/1203721175349653504?s=20

overwhelming the answer was 1 gen / yr. and an appropriate citation https://doi.org/10.1890/0012-9658(2002)083[1006:GTINSO]2.0.CO;2

**Comment by jeromekelleher** [comment]
Great, thanks @andrewkern, we have generation time sorted in #296

Any takers for A thal. population size citation?

**Comment by gtsambos** [comment]
> Any takers for A thal. population size citation?

One of the researchers in my lab who did a postdoc on arabidopsis said it should be more like 10 000 rather than 1000, but like with the human data, it's a bit hard to find a non-population-specific estimate

**Comment by gtsambos** [comment]
How about this one: (disclaimer: the person I consulted, Ashley Farlow, was an author on this paper)

> Alonso-Blanco, C., et al (2016). 1,135 Genomes Reveal the Global Pattern of Polymorphism in Arabidopsis thaliana. Cell, 166(2), 481–491. [https://doi.org/10.1016/j.cell.2016.05.063](https://doi.org/10.1016/j.cell.2016.05.063)

See figure 4A for estimation of coalescence rates over time. It does look like 10^3 is a better estimate.

**Comment by gtsambos** [comment]
Also, I was notified about this paper, which seems to use a bit more data and models a bigger range of arabidopsis populations than the ones currently in the catalog. 

> Hsu, C.‐W., Lo, C.‐Y. and Lee, C.‐R. (2019), On the postglacial spread of human commensal Arabidopsis thaliana: journey to the East. New Phytol, 222: 1447-1457 [https://doi.org/10.1111/nph.15682](https://doi.org/10.1111/nph.15682)

**Comment by jeromekelleher** [comment]
Thanks for chasing this @gtsambos, this is perfect.
