### ISSUE TITLE
QC for Huber 3 Epoch model

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/stdpopsim#301]
See #228 for references.

Initial model implemented in #270.

Who would like to take this on?

**Comment by ndukler** [comment]
I can do this today

**Comment by jeromekelleher** [comment]
Thanks @ndukler, all yours.

**Comment by ndukler** [comment]
We can close this now @jeromekelleher

**Comment by jeromekelleher** [comment]
Can you mention the PR where this was closed for information please @ndukler?

**Comment by ndukler** [comment]
PR #312
