### ISSUE TITLE
Rename Model class to DemographicModel?

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/stdpopsim#303]
The models.Model class may be a bit too general a name, since it's likely that we'll also have to work with different mutation models and perhaps selection models etc as well.

Rename it to DemographicModel so that the API will be forward compatible before 0.1.0 is released?

Also, should be change the CLI to use ``--demographic-model``, ``-d`` for similar reasons?

**Comment by grahamgower** [comment]
This does seem inevitable...

**Comment by jeromekelleher** [comment]
Closed in #307.
