### ISSUE TITLE
Genome-wide recombination rate for `genome` class

### ISSUE THREAD

**Issue by jgallowa07** [popgensims/stdpopsim#31]
Add a genome-wide recombination rate to the `genome` class. I'm happy to implement this today. The only question is, should it be created and stored as an attribute at the instantiation of a `genome` object, or, should there simply be a method which computes this when needed.

**Comment by jeromekelleher** [comment]
Great, thanks @jgallowa07. I'd imagine computing this on-demand using an attribute getter function is the way to go (i.e., using the ``@property`` decorator).

**Comment by jgallowa07** [comment]
What if instead we made a method for both `Genome` and `Chromosome` that computed the weighted mean recombination rate given a map?

i.e. for `Chromosome`:
`    def mean_map_recombination_rate(self,map_name=None):
        """
        Returns :float: a per-base recombination rate representing the 
        weighted average for all the given recombination map 
        chromosomal windows.
        """
        if map_name is None:
            map_name = self.default_genetic_map
        recombination_map = self.recombination_map(map_name)
        mean_recombination_rate = 0
        prev_pos = 0
        positions = recombination_map.get_positions()
        rates = recombination_map.get_rates()
        for pos,rate in zip(positions,rates):
            normalized_weight = (pos - prev_pos) / self.length
            mean_recombination_rate += rate * normalized_weight
        return mean_recombination_rate`

and for `Genome` ...

`    def mean_map_recombination_rate(self,map_name=None):
        if map_name is None:
            map_name = self.default_genetic_map
        mean_recombination_rate = 0
        for chromosome in self.chromosomes:
            chromosome = self.chromosomes[chromosome]
            print(chromosome.name)
            normalized_weight = chromosome.length / self.genome_length
            cont = (chromosome.mean_map_recombination_rate(map_name))*normalized_weight
            print(cont)
            mean_recombination_rate += cont
        return mean_recombination_rate
`

thoughts?

**Comment by jeromekelleher** [comment]
LGTM also @jgallowa07. I think we'd also want the simple weighted mean rate from the Genome definitions though.

**Comment by jgallowa07** [comment]
Totally agree, that should be quite easy as well.

**Comment by jgallowa07** [comment]
I'm closing this issue as we've got it covered here #34
