### ISSUE TITLE
Add mutation_rate_citation and recombination_rate_citation to Genome

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/stdpopsim#317]
As discussed in #316, we have no way to register citations for mutation rate and recombination rate estimates. 

Adding attributes ``mutation_rate_citation`` and ``recombination_rate_citation`` to the Genome object seems like the logical thing to do. We would need to think about how to use these citations when generating the list of citations as well.

**Comment by grahamgower** [comment]
I'll take care of this.

**Comment by jeromekelleher** [comment]
Was this closed in #323?

**Comment by grahamgower** [comment]
> Was this closed in #323?

Yep.
