### ISSUE TITLE
Change species ID scheme to CamelCase

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/stdpopsim#318]
Following the standardisation of demographic model IDs in #122/#310, we decided to change the species ID scheme to CamelCase, e.g. HomSap, DroMel, etc.

This should be mostly a search and replace, but we will need to update the catalog generation code to convert the IDs to lowercase when generating labels (see the ``get_demographic_model_id`` function), as Sphinx only allows lowercase section labels (I think).

Any volunteers?

**Comment by jeromekelleher** [comment]
Any takers? This is a straightforward change.

**Comment by andrewkern** [comment]
okay i got this

**Comment by andrewkern** [comment]
closed by https://github.com/popgensims/stdpopsim/pull/324
