### ISSUE TITLE
No `genetic_map_GRCh37_chrY.txt` in HapmapII_GRCh37_RecombinationHotspots.tar.gz

### ISSUE THREAD

**Issue by jgallowa07** [popgensims/stdpopsim#32]
My lack of bioInformatics knowledge leads me to believe leaving out the Y chromosome is intentional. There also happens to be 3 files for the X Chromosome. 

Either way, 
```
180         map_file = os.path.join(self.map_cache_dir, self.file_pattern.format(name=name))
181         return msprime.RecombinationMap.read_hapmap(map_file)
```
in `stdpopsim/genetic_maps` heuristic won't quite work here (I think). 

It will throw a `FileNotFoundError` if you do the following 
```
import msprime
from stdpopsim import homo_sapiens

for chrom in homo_sapiens.genome.chromosomes:
    chrom = homo_sapiens.genome.chromosomes[chrom]
    chrom.recombination_map()
```

**Comment by ndukler** [comment]
Yeah, there is no recombination on the y (mostly).

**Comment by jeromekelleher** [comment]
Hmm, good catch @jgallowa07, we'll need to do something about this. Any ideas?

**Comment by jgallowa07** [comment]
The easiest thing to me seems like identifying whether there is a genetic mapping for each chromosome when it's instantiated; and then simply returning something trivial (or None) when calling chromosome.recombination_map (and possibly mutation rate map down the line)

Alternatively, Is there any reason we can't conceptually couple the `genetic maps` locations with `genomes`, as opposed to hard-coding positions?

**Comment by jeromekelleher** [comment]
> The easiest thing to me seems like identifying whether there is a genetic mapping for each chromosome when it's instantiated; and then simply returning something trivial (or None) when calling chromosome.recombination_map (and possibly mutation rate map down the line)

Good idea. I guess in the case of the Y chromosome we should return a map that says we have zero recombination rate between the start and end. So, *if* it's a chromosome we know about and there's no map, we return a flat map with zero recombination?

> Alternatively, Is there any reason we can't conceptually couple the genetic maps locations with genomes, as opposed to hard-coding positions?

I'm not following this; could you elaborate a bit please?

**Comment by jgallowa07** [comment]
> > The easiest thing to me seems like identifying whether there is a genetic mapping for each chromosome when it's instantiated; and then simply returning something trivial (or None) when calling chromosome.recombination_map (and possibly mutation rate map down the line)
> 
> Good idea. I guess in the case of the Y chromosome we should return a map that says we have zero recombination rate between the start and end. So, _if_ it's a chromosome we know about and there's no map, we return a flat map with zero recombination?

This should be pretty easy. I'll do this before submitting a pull request for #31 

> 
> > Alternatively, Is there any reason we can't conceptually couple the genetic maps locations with genomes, as opposed to hard-coding positions?
> 
> I'm not following this; could you elaborate a bit please?

Hmm, I guess what I was saying is that the ` _chromosome_data` defined for each model won't always match the `positions` given in a genetic recombination map/mutation map. And we should clearly define the behavior for this.

Otherwise it doesn't make sence (to me) to run a coalescent with length defined as less or greater than that of the `msprime.recombination_map`

The following might confuse the user ... 
```
import msprime
from stdpopsim import homo_sapiens
from stdpopsim import genetic_maps

for chrom in homo_sapiens.genome.chromosomes:
    chrom = homo_sapiens.genome.chromosomes[chrom]
    cm = chrom.recombination_map()
    print("chrom_length: ",chrom.length)
    print("map_length: ",max(cm.get_positions()))
    if(chrom.length == int(max(cm.get_positions()))):
        print("fine")
    elif(chrom.length < int(max(cm.get_positions()))):
        print("defined length too small")
    else:
        print("defined length too long")
```

**Comment by jgallowa07** [comment]
I'll go with the simple fix for now. But it may be nice for Chromosomes (and their lengths) to be accessed through the genetic map instead (as well?)

**Comment by jeromekelleher** [comment]
> Otherwise it doesn't make sence (to me) to run a coalescent with length defined as less or greater than that of the msprime.recombination_map -- Although I'm suremsprime has some behavior for this?

The length is defined by the recombination map in msprime, so there's no ambiguity here. Perhaps we should raise a warning if the sizes of the map/genome doesn't match? There's not much we can do about this though. Suppose one map is for GRCh36 and another is for GRCh38 --- then one of them isn't going to match the sizes on the Genome definition.  I'm not sure it's worth worrying about to be honest.

**Comment by jgallowa07** [comment]
I'm going to close this issue, I think we have it under control in #33
