### ISSUE TITLE
General question about dev.

### ISSUE THREAD

**Issue by jgallowa07** [popgensims/stdpopsim#35]
@jeromekelleher Is there an easy way to do the flake8 tests on code before it's committed?
I know that in `.git/hooks/` there is a `pre-commit.sample` but simply changing the name doesn't achieve the same testing as circleCI.

I think we need something along the line of `exec flake8 --max-line-length 89 ../../stdpopsim ../../tests` within this executable, but I'm not sure.

could you maybe give a short explanation on how to do the CircleCI tests before committing?

**Comment by jeromekelleher** [comment]
You can alway just run flake8 directly yourself, like
```
$ flake --max-line-length 89 stdpopsim tests
```
I use the vim [flake8 plugin](https://github.com/nvie/vim-flake8) which is super useful, gives you the flake8 stuff in the quickfix list which really helps.

In the pre-commit hook, you need to add the ``exec flake8`` line *before* the end. Here's the last few lines of mine:

```
exec flake8 --max-line-length 89 setup.py stdpopsim tests

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
```

The last two really help with maintaining sanity!

Perhaps we should add some of this to the developer docs?

**Comment by jgallowa07** [comment]
Awesome, this is going to save a LOT of my sanity ha. And yes, we should include this in dev docs. I'll do that now.

**Comment by jgallowa07** [comment]
closing this due to #36

**Comment by jgallowa07** [comment]
#
