### ISSUE TITLE
License is actually GPL

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/stdpopsim#37]
The license for the package is currently marked as MIT, but after thinking about this a bit I think it's not correct. The stdpopsim package imports msprime, which is GPL, and stdpopsim is therefore also GPL. This is annoying, but can't be helped.

@molpopgen, do you agree with this?

**Comment by molpopgen** [comment]
I believe this to be correct.  The "derivative product" concept seems to
apply here.  But, I am not a lawyer 😉.

**Comment by grahamgower** [comment]
I think that the GPL will apply to *distribution* of stdpopsim as a whole. But this should not preclude individual components within stdpopsim being MIT licensed. In practice, someone should be permitted to take the sources and use them under the terms of the MIT license. Of course, if they use the parts with msprime imports, then they will also be bound to distribute under the terms of the GPL. I think this is more or less the same as MIT-licensed code linking against a GPLed library.

https://opensource.stackexchange.com/questions/8134/if-mit-licensed-code-links-to-gpl-licensed-code-what-should-be-the-license-of-th

**Comment by jeromekelleher** [comment]
This is a tricky issue. I think since we're using the msprime DemographicEvent infrastructure quite centrally, it would be difficult to see how any code within stdpopsim doesn't depend on this. It's annoying the GPL is like this, but that's where we are and there's not much we can do about it. If you feel strongly about parts of stdpopsim not being GPL, I'm sure we can work something out though. It'd be more efficient to discuss offline, so let me know if you'd like to chat about it.
