### ISSUE TITLE
Renaming does not work properly if several threads are downloading maps concurrently.

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/stdpopsim#38]
The code for figuring out when to download a genetic map depends on checking for the corresponding files. So does substituting default zero maps, as introduced in #33. This means we are always returning zero maps at the moment. 

(HT to @petrelharp here; I wouldn't have spotted this except for your warning!)

**Comment by jgallowa07** [comment]
I was thinking about this when doing the flat maps. Maybe, we should store chromosomes and their metadata in some data structure (dictionary?) as a property of the genome?

This way we can query the data struct for an existing chromosome map instead of the file path?

**Comment by jeromekelleher** [comment]
One simple thing we could do is look for the directory path when asking if the Map exists rather than a specific file. This would work quite well I think.

I don't want to have to walk the file system checking for all maps at startup, this would slow down module import a lot of we had lots of species and maps.

**Comment by jeromekelleher** [comment]
Hmmm, not sure this actually is a problem. Looking into it...

**Comment by jeromekelleher** [comment]
Ouch. Actually, the problem in https://github.com/andrewkern/analysis/issues/2 is that this doesn't work when we've got several threads that are downloading the same map simultaneously.

Renaming the bug accordingly.

**Comment by jeromekelleher** [comment]
There is still a problem here and it's possible to get a zero-map where you shouldn't. This code will raise a warning if the cache isn't there:
```
    chrom = homo_sapiens.genome.chromosomes[args.chromosome]  
    recomb_map = chrom.recombination_map()
```
