### ISSUE TITLE
Refactor chromosome definitions

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/stdpopsim#51]
PR #45 adds the ability to reproducibly run standard simulations from the command line, which is a real win in terms of usability. During the process of working through this change, it's become clear that the way that genome/chromosome/genetic map information is laid out is really quite poor and we should refactor it. 

One possibility I've tried out is to have a 'factory function' which would return a chromosome with the appropriate instance variables set. See a rough version [here](https://github.com/popgensims/stdpopsim/pull/45/files#diff-1b018f8c54343a41e051a8f902702c11R116). Clearly we'd need something that would work for different species as well, but I guess it wouldn't be the end-of-the-world to define a ``chromosome_factory`` function in each of the species modules. So, from a users perspective, they call

```python
chrom = homo_sapiens.chromosome_factory("chr22", "HapMapII_GRCh37")
```
and the returned object will have a recombination map created from the appropriate genetic map and the default mutation rate for this chromosome. If the user calls:
```python
chrom = homo_sapiens.chromosome_factory("chr12")
```
They'll get back a chromosome object with the length appropriate for chr12, the default mutation rate and a flat recombination map with the default recombination rate.

One thing that turned out to be pretty useful for testing the CLI is to add an option to return a *fraction* of a chromosome. So, if we did
```python
chrom = homo_sapiens.chromosome_factory("chr12", length_multiplier=0.1)
```
which will return a chromosome that's 1/10th of the length of chr12. I think this is generally a useful thing to be able to do --- sometimes there's really no point in simulating a whole chromosome.

Does this refactoring sound OK to everyone? Any thoughts on what else we'd need to include in the API, or a better naming scheme?

**Comment by jeromekelleher** [comment]
pinging @petrelharp and @jgallowa07 for opinions here...

**Comment by jgallowa07** [comment]
I like the Idea. It's true that our current setup is confusing

to be clear, are you suggesting disassociating genetic maps from the chromosomes/genomes? meaning no `genome.default_genetic_map`, or `chromosome.default_genetic_map`? and no `chromosome.recombination_map()` method?

**Comment by jeromekelleher** [comment]
Yeah, I think so. The ``chromosome_factory`` (or whatever) function will return a simple ``Chromosome`` object that just has some basic attributes --- all the instantiation will be done behind the scenes. We can then organise the lookup tables however we want within the module. Seems a lot simpler.

**Comment by jgallowa07** [comment]
Right, but do those simple `Chromosome` objects replace our current heuristic with the genome-chromosome relationship? 

I think the `chromosome factory` is a useful tool for the association of genetic maps to chromosomes but I don't necessarily see it replacing the `model.genome`. Shouldn't the factory just return an `msprime recombination_map` instead of a chromosome?

**Comment by jeromekelleher** [comment]
> Right, but do those simple Chromosome objects replace our current heuristic with the genome-chromosome relationship?

I'm not sure how the 'back end' would work at the moment to be honest. My main point is that the user would be isolated from this complexity. All they would say is 'give me human chromosome 22 for genetic map 'HapMap' and some other stuff', and they would get back a ``Chromosome`` object with the appropriate mutation rate, recombination rate, length and msprime RecombinationMap. The current infrastructure is very clunky and complicated, and I want to hide the details of how we define our 'lookup tables' for mutation, recombination rates etc from the user.

So, to be clear, I want the end API to look like
```python
chrom = homo_sapiens.chromosome_factory("chr22", genetic_map="HapMapII_GRCh37")
ts = msprime.simulate(
     sample_size=10, recombination_map=chrom.recombination_map,
     mutation_rate=chrom.mutation_rate)
```
Or, you could have
```python
chrom = homo_sapiens.chromosome_factory("chr1", length_scale=0.01)
ts = msprime.simulate(
     sample_size=10, 
     recombination_rate=chrom.recombination_rate,
     length=chrom.length,
     mutation_rate=chrom.mutation_rate)
```
This simulates 1% of human chromosome 1. You could get the same effect by
```python
chrom = homo_sapiens.chromosome_factory("chr1", length_scale=0.01)
ts = msprime.simulate(
     sample_size=10, 
     recombination_map=chrom.recombination_map,
     mutation_rate=chrom.mutation_rate)
```
as by default we'd return a flat recombination map with the default rate. 

Does this make sense?

**Comment by jeromekelleher** [comment]
Or, I guess we could just have 
```python
chrom = stdpopsim.chromosome("homo_sapiens", "chr22", genetic_map="HapMapII_GRCh37")
```
having it per species would save a bit of typing and avoid spelling errors probably. But maybe it's more readable this way?

**Comment by jgallowa07** [comment]
This totally makes sense, and I think It's a great idea! This will probably make the CLI easier to implement. 

One thing I think is nice for anyone who does want to use the python module is to be able to iterate through chromosomes. It seems intuitive that the species has a 'Genome' that points them towards anything they might need, e.g. chromosome names, genetic maps registered to that species, and other useful things like the genome-wide, mean recombination rate -- Just a thought

But overall I say do it, I'm happy to help as well!

**Comment by jeromekelleher** [comment]
Good idea on having some access to the chromosome names for a species. We'll definitely want that somewhere.

**Comment by jeromekelleher** [comment]
Done in #110.
