### ISSUE TITLE
appdirs dependency not correctly defined?

### ISSUE THREAD

**Issue by ndukler** [popgensims/stdpopsim#53]
I installed stdpopsim from my cloned repo and tried to import it but got the following error message:

ModuleNotFoundError: No module named 'appdirs'

I'm not really familiar with python but I'd imagine this indicates that something is missing in the dependency description for stdpopsim?

**Comment by ndukler** [comment]
Although it does seem to be in development so I'm not really sure?

**Comment by jeromekelleher** [comment]
Did you install using ``python3 setup.py install`` or using ``pip``?

**Comment by ndukler** [comment]
I used conda

**Comment by ndukler** [comment]
I used python3 setup.py install

**Comment by jeromekelleher** [comment]
``setup.py install`` doesn't install any requirements, and wouldn't be the way to install this for a released version --- this would be either by ``pip install stdpopsim`` or ``conda install stdpopsim`` (assuming we make a conda package). As a developer, use ``conda install -r requirements/devolpment.txt``. This is covered in the [dev docs](https://stdpopsim.readthedocs.io/en/latest/development.html) so I'm doing to close the issue.

**Comment by ndukler** [comment]
Ah, my apologies, thanks!
