### ISSUE TITLE
Change model.equals to 'verify' and raise an exception

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/stdpopsim#54]
Copied from #52.

> @jeromekelleher As I kinda expected, my implementation of the model did not match the production version. Would it be a good idea to have a diff() function that would report model differences per epoch in a format similar to the DemographyDebugger() program? Otherwise I'm just comparing two DemographyDebugger() outputs which is doable, but feels clumsy.

What we could do is change the definition of ``Model.equals`` so that it raises an exception if models differ rather than returning true/false; this would at least say *where* the difference occurs). So, we'd change the name to ``check_equal``, which would raise a ValueError with meaningful messages telling us which bits of the models differ. The existing tests can be rejigged to use this easily enough.

Would this be useful for the QC process @carjed, @ndukler?

**Comment by ndukler** [comment]
This would be very useful!

**Comment by jeromekelleher** [comment]
OK, will do.
