### ISSUE TITLE
QC for Sheehan-Song Three Epoch Model (Drosophila)

### ISSUE THREAD

**Issue by ndukler** [popgensims/stdpopsim#66]
When you have a chance can you just throw in the paper of reference and the population id indices for the production msprime implementation @andrewkern. Thanks!

**Comment by ndukler** [comment]
Sheehan and Song:
https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004845

**Comment by ndukler** [comment]
Erm, so @andrewkern you're gonna love this but we have more interesting issues related to a disagreement in the number of generations. If I understand how to do this correctly, the coalescent units to # of generations is usually calculated as 4N for diploid individuals. However if you check the result of t_1 * 4 * N_ref = 0.5 * 4 * 100,000 and convert to years using 10 gen/yr it equals 20,000yrs. This is in contrast to the 10,000yrs they show in figure 3. I'm not sure why (maybe it has something to do with simulating things as haplotypes), but I think they did the coalescent times to generations calculation as t_1 * 2 * N_ref for the bottleneck and  (t_1+t_2) * 2 * N_ref for the ancestral size events. The t_1+t_2 bit is because is figure 3 the second time is clearly greater than 100,000 and just about right for 110,000.

**Comment by andrewkern** [comment]
interesting.... i'll go look back at what they say here

**Comment by andrewkern** [comment]
so i agree that their Figure 3 looks weird, but they are using `msms` for simulations which explicitly takes units of time as 4Ne generations. Maybe they are scaling time wrong in the figure?

**Comment by ndukler** [comment]
Should we email then and ask? I've corresponded with Sara before.

**Comment by andrewkern** [comment]
sure yes-- ask Sara if she remembers

**Comment by ndukler** [comment]
PR #81 accepted so I'm closing this
