### ISSUE TITLE
QC for Li-Stephans model (Drosophila)

### ISSUE THREAD

**Issue by ndukler** [popgensims/stdpopsim#67]
When you have a chance can you just throw in the paper of reference and the population id indices for the production msprime implementation @andrewkern. Thanks!

**Comment by ndukler** [comment]
Li and Stephan:
https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.0020166

The Li and Stephan model is a two population case. In that case index 0 is the African population and index 1 is the european popn

**Comment by ndukler** [comment]
Are the epoch time off by a factor of 10 in the production model @andrewkern ? In the paper they say " per generation (assuming ten generations per year)", and give all the event times in years so I multiplied the event times by 10. Would this be correct?

**Comment by ndukler** [comment]
Actually it looks like we're off by a factor of 100. I think you may have divided by 10 instead of 0.1.

**Comment by ndukler** [comment]
Submitted PR #77

**Comment by andrewkern** [comment]
Ah yes! It looks like I divided by 10 rather than by 0.1!! Great catch @ndukler. So what is our SOP at this point? Do I make changes to the `master` branch? Do we merge your PR?

**Comment by ndukler** [comment]
Submit a PR to the master branch, then once it's accepted, I'll rebase my PR against it

**Comment by andrewkern** [comment]
okay will do right now

**Comment by andrewkern** [comment]
@ndukler just pushed my PR to master for your review

**Comment by ndukler** [comment]
@andrewkern Reviewed, you merge it into master now

**Comment by ndukler** [comment]
@andrewkern Thanks! It looks like everything passed so PR #77 can be merged in and I'll close this issue.
