### ISSUE TITLE
QC for fly models

### ISSUE THREAD

**Issue by andrewkern** [popgensims/stdpopsim#70]
Hey @ndukler-- here are the paper's associated with the fly models:

Sheehan and Song:
https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004845

Li and Stephan:
https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.0020166

The Li and Stephan model is a two population case. In that case index 0 is the African population and index 1 is the european popn

**Comment by jeromekelleher** [comment]
I guess we should port these into issues #66 and #67, closing this issue?

**Comment by ndukler** [comment]
Done, this can be closed.

**Comment by ndukler** [comment]
Thanks @andrewkern !
