### ISSUE TITLE
include species.generation_time, in each module

### ISSUE THREAD

**Issue by jgallowa07** [popgensims/stdpopsim#73]
While doing some analysis with `stdpopsim` I realized it might be nice (mostly for generalized code) to have default generation time associated with each model. Thoughts @jeromekelleher @andrewkern @petrelharp?

**Comment by jgallowa07** [comment]
even more, It might be nice to have `name` attributes for genetic_maps, models, etc.

**Comment by andrewkern** [comment]
yes definitely we should assign default generation times. An decent defaults would be 25 years / gen for humans, 1 year / gen for Arabidopsis, and 0.0666 year/gen for Drosophila I think

**Comment by jeromekelleher** [comment]
Good idea! This is an attribute of the species rather than the model though, isn't it?

**Comment by andrewkern** [comment]
yes indeed

**Comment by jgallowa07** [comment]
oops, species Is what I was shooting for. 

Cool, I'll submit the PR when I have some free time.

**Comment by petrelharp** [comment]
Sounds good!

I've taken 27 years as a better default (reflecting long-term averages, maybe) for humans:
     http://dx.doi.org/10.1002/ajpa.20188

**Comment by andrewkern** [comment]
closing this down as we are dealing with this in a PR now

**Comment by jeromekelleher** [comment]
It's been changed to ``default_generation_time``, which is better I think.
