### ISSUE TITLE
Developing a standard demographic model documentation format

### ISSUE THREAD

**Issue by ndukler** [popgensims/stdpopsim#83]
To make model documentation easier I would like to standardize the format. The current sections I am thinking of are:
- Model description: describes general scenario
- Population indices: lists populations in model and their indices
- Source paper citation: provides a citation of the key paper for the model

Are there any other sections that we should have? Do we want to go into more detail about the model construction, etc. ?

**Comment by jeromekelleher** [comment]
This looks great, thanks @ndukler. One thing that might be handy to know is that sphinx supports [math markup](https://shimizukawa-sphinx.readthedocs.io/en/latest/ext/math.html). It'll be good to talk through some details at the meeting today.

**Comment by ndukler** [comment]
Adding three additional sections:

- Model name
- CLI usage example
- Parameter table

**Comment by ndukler** [comment]
I think this is settled. I'll add some documentation to the dev docs about this but closing for now.
