### ISSUE TITLE
Add population metadata

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/stdpopsim#89]
Tskit allows arbitrary metadata to be assocated with populations. Msprime 0.7.1 just added the facility to use metdata with [PopulationConfiguration](https://msprime.readthedocs.io/en/stable/api.html#msprime.PopulationConfiguration) objects, so we now can add some descriptive stucture to each population. This should really help with debugging. 

I suggest we add something simple like, e.g.
```python
metadata={
    "name": "AFR", 
    "description": "The contemporary African population"
}
```

Any thoughts @ndukler, @andrewkern?

**Comment by ndukler** [comment]
I like this. My only thought is that the interpretation of the population changes over time (e.g. European -> OOA) but I see no downside to doing this. Do you want me to go back through the models and add this?

**Comment by jeromekelleher** [comment]
> I like this. My only thought is that the interpretation of the population changes over time (e.g. European -> OOA) but I see no downside to doing this.

Good point. Maybe it would be better if we created different populations for things like the ancient OOA? The overhead in msprime is minimal, and I guess is just needs an extra MassMigration to implement. What do you think?

> Do you want me to go back through the models and add metadata to the PopulationConfiguration objects? 

That would be amazing - you are a legend!

> It also means we'll have to enforce the version number of the msprime package strictly; do we want to do that?

I think that's fine. We just put in msprime >=0.7.1 in setup.py and it'll be taken care of.

**Comment by andrewkern** [comment]
this functionality sounds great @jeromekelleher. creating different populations associated with metadata sounds just about ideal, but if we did that I fear we would break the `DemographyDebugger.coalescence_rate_trajectory()` function...

**Comment by andrewkern** [comment]
what do you think @jgallowa07 @petrelharp?

**Comment by jgallowa07** [comment]
> this functionality sounds great @jeromekelleher. creating different populations associated with metadata sounds just about ideal, but if we did that I fear we would break the `DemographyDebugger.coalescence_rate_trajectory()` function...

I don't see how it would break the functionality of `DemographyDebugger.coalescence_rate_trajectory()` ... but maybe I'm missing something here.

**Comment by andrewkern** [comment]
worried about creating different populations linked by mass migration-- still ok?

**Comment by jgallowa07** [comment]
The mass migration case was taken care of (checkout https://github.com/tskit-dev/msprime/blob/21783d1522e8b8ebfe16f1333cf397f64c3b1954/msprime/simulations.py#L1639), does the metadata mess with this @andrewkern?

**Comment by petrelharp** [comment]
The default plots might get messed up, but I can fix them if so. This will avoid other confusion.

**Comment by ndukler** [comment]
I think this all sounds good. I can make the necessary alterations to the QC models, but someone else should make the alterations to the production models so that we maintain our QC process. Otherwise I might just make the mistake in both.

**Comment by ndukler** [comment]
@jeromekelleher msprime 0.7.1 does not appear to be on conda-forge. I only see up to 0.7.0.

**Comment by jeromekelleher** [comment]
Sorry about this @ndukler, I'm having trouble with the conda-forge builds. The windows builds are currently broken - see [here](https://github.com/conda-forge/msprime-feedstock/pull/29).

**Comment by jeromekelleher** [comment]
Released on conda-forge now @ndukler, all should be good.

**Comment by ndukler** [comment]
Thanks!

**Comment by jeromekelleher** [comment]
Done.
