### ISSUE TITLE
Generation times as an attribute of model class

### ISSUE THREAD

**Issue by jradrion** [popgensims/stdpopsim#90]
I raised this issue over in analysis, but I probably should have posted it here. Andy and I noticed that generation times might be better implemented as a class attribute for each of the models. Currently these times are hard-coded into some of the models, however they are provided to some of the n_t analysis programs as user-specified arguments, leading to potential misspecification issues.

**Comment by jeromekelleher** [comment]
Sounds good, @andrewkern is following up in #92

**Comment by andrewkern** [comment]
closing down
