### ISSUE TITLE
spikes in the SFS when simulating with genetic map

### ISSUE THREAD

**Issue by andrewkern** [popgensims/stdpopsim#93]
Hey all--

@jradrion and I have been looking at the SFS produced by human models in an effort to debug stairwayplot a bit. We've noticed that simulating under a genetic map instead of a constant rates leads to strange spikes in the SFS. 

Presumably these spikes are caused by low recombination regions of the simulated chromosome? As an empiricist, one would want to drop such regions from downstream analysis- should we consider doing the same here? 

A minimum working example of this comparison can be found [here](https://gist.github.com/andrewkern/13d102b988bb17114fded1cf3fac7a48). Run it a few times if you don't see a bigger spike in the genetic map case in the first run or two. 

representative output looks like this
```
$ python testSFS.py
SFS with genetic map
[0.         0.41105418 0.15667424 0.10971423 0.10006515 0.03928301
 0.10844646 0.02769708 0.02285493 0.02421073]
SFS with constant rate
[0.         0.43990996 0.17313905 0.10304832 0.07146539 0.05412743
 0.04816482 0.03857653 0.0367551  0.03481339]
```
notice the freq=6 bin with the genetic map

thoughts?

**Comment by dschride** [comment]
Just an update on this. I happened to have some forward simulations sitting around that used the Kong 2010 recombination map. Rather than from one entire chromosome/genome, these simulations are of random 1 Mb chunk (i.e. each replicate draws a random region from the Kong genetic map and uses that). Sample size is 100. I aggregated the SFS across these replicates and plot the result below (about 1.6 million SNPs in total). Not seeing any bumpiness here, so this might imply that the presence of low-recombining regions will not necessarily yield a spiky SFS. These are under the Tennessen Euro model (no admixture or migration), but results are similar under equilibrium--different looking SFS obviously but no bumps.

![image_2019_06_20T03_59_16_724Z](https://user-images.githubusercontent.com/41480286/59856528-17a18a80-9345-11e9-98b0-6f300ff915aa.png)

**Comment by andrewkern** [comment]
just talked this over with @petrelharp for a bit. probably the best thing to do is to LD prune the set of SNPs generated for input to stairwayplot. We will implement this and report back.

**Comment by andrewkern** [comment]
Well naive LD pruning didn't fix anything. Here is the updated [MWE](https://gist.github.com/andrewkern/13d102b988bb17114fded1cf3fac7a48). I've used the `locate_unlinked()` function in `scikit-allel` for this simple pruning.

Here are results from a representative run:
```
SFS with genetic map
[0.         0.52620745 0.15690444 0.07364625 0.07311886 0.03666151
 0.03142172 0.02815536 0.0254504  0.04843402]
----------------------

SFS with genetic map, LD pruned
[0.         0.80934643 0.02675246 0.00372503 0.03284795 0.08195056
 0.01286827 0.         0.00372503 0.02878429]
----------------------

SFS with constant rate
[0.         0.43384952 0.17655277 0.10363575 0.0750547  0.05520956
 0.04819054 0.03935364 0.03571789 0.03243562]
----------------------

SFS with constant rate, LD pruned
[0.         0.81824433 0.11849645 0.02406601 0.0075636  0.
 0.0009168  0.002292   0.0061884  0.02223241]
```

I'm not confident that `scikit-allel` is doing what we want but haven't yet gone down that rabbit hole...

**Comment by jradrion** [comment]
It certainly looks like `locate_unlinked` is not doing what we want here. I changed the rsq threshold to 0.99, and as you can see nearly 90% of sites are still filtered out and the SFS is very strange.
![sfs test](https://user-images.githubusercontent.com/20053488/59876259-f5653800-9357-11e9-8203-dcd0d1a2213d.png)

**Comment by petrelharp** [comment]
Wierd.

>  I changed the rsq threshold to 0.99
Do you mean `threshold = 0.01`? That would be [more stringent](https://scikit-allel.readthedocs.io/en/stable/stats/ld.html#allel.locate_unlinked).

**Comment by andrewkern** [comment]
i think we are going to have to write our own function here

**Comment by jeromekelleher** [comment]
Will the LDCalculator in tskit be of any use here?

**Comment by jradrion** [comment]
@petrelharp 
No, i used threshold = 0.99. My understanding of `locate_unlinked` is that this should retain all sites with rsq <= 0.99, so less stringent. So apparently ~90% of sites have rsq = 1.0?

**Comment by petrelharp** [comment]
> So apparently ~90% of sites have rsq >= 0.99?

That is worrisome, if true.

>LDCalculator

There's some info on this very question in [this thread](https://groups.google.com/forum/?#!msg/msprime-users/cqsa4mn73p8/ey1WwwsuAQAJ).

**Comment by jradrion** [comment]
![sfs test thresh0 1](https://user-images.githubusercontent.com/20053488/60906454-02c16400-a22c-11e9-8e74-7f34323b959e.png)
Here are the differences in LD pruning using the `locate_unlinked` function implemented in scikit-allel and the `LdCalculator` function in msprime

**Comment by jeromekelleher** [comment]
Following up on this from the call, I think it would be good to try:

1. Run a simulation with a single population & no structure with a genetic map; do we get spikiness?
2. If we do, run the same model/recombination map in SLiM. Do we get spikiness? If yes, it's likely a real effect; if no, looks like a bug in msprime.
3. If not, try to track down the minimum structure that we'd need to reproduce it (do we need two populations?). If it's simple enough to implement in SLiM, try the same logic as 2.

**Comment by jeromekelleher** [comment]
I think this issue was resolved, right? IIRC, it came down to large sections of the genome with no recombination was the problem, which we resolve by masking these out of analyses.
