### ISSUE TITLE
"true" Ne

### ISSUE THREAD

**Issue by petrelharp** [popgensims/stdpopsim#95]
Over at https://github.com/tskit-dev/msprime/pull/779 I have implemented a method that calculates the "true" Ne at a particular time - as the mean TMRCA - for comparison with methods that infer a single Ne (as opposed to a coal rate as a function of time). When that gets merged to msprime, shall we add them to @ckyriazis's plots?

**Comment by jeromekelleher** [comment]
Seems like a nice addition to me - any reason not to?

**Comment by petrelharp** [comment]
Don't think so. This is mostly a reminder for me to do it.

**Comment by jeromekelleher** [comment]
Is this in the right repo @petrelharp? Seem more like something for the analysis repo.

**Comment by petrelharp** [comment]
yep, but this has been done anyhow.
